### ISSUE TITLE
Argumentfehler

### ISSUE THREAD

**Issue by piepert** [DeltaCoding/DeltaBrain#1]
Hey! Ist ein bisschen blöd, wenn man das Programm startet und man bekommt eine ArrayIndexOutOfBoundsException, oder? Mach am besten ne Abfrage dazu rein, wie

```java
if (args.length == 0) {
	System.out.println("Give me a file!");
	return;
}
```

**Comment by DeltaCoding** [comment]
Done, danke für die Meldung.
